name: Install SonarQube on Windows

on:
  workflow_dispatch:

jobs:
  install-sonarqube:
    runs-on: windows-latest

    steps:
      - name: Download and Extract SonarQube
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"

          # Create directory if not exists
          $destinationPath = "$env:USERPROFILE\sonarqube"
          if (!(Test-Path $destinationPath)) {
            New-Item -ItemType Directory -Path $destinationPath | Out-Null
          }

          # Download
          $zipPath = "$destinationPath\sonarqube.zip"
          Invoke-WebRequest -Uri "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.4.1.88267.zip" -OutFile $zipPath

          # Extract
          Expand-Archive -Path $zipPath -DestinationPath $destinationPath -Force

          # Verify and navigate to extracted directory
          $sonarBinPath = Join-Path $destinationPath "sonarqube-10.4.1.88267\bin\windows-x86-64"
          if (!(Test-Path $sonarBinPath)) {
            Write-Error "SonarQube binary path not found: $sonarBinPath"
            exit 1
          }

          Set-Location $sonarBinPath
          Start-Process -FilePath ".\StartSonar.bat"
