name: Install SonarQube on Windows

on:
  workflow_dispatch:

jobs:
  install-sonarqube:
    runs-on: self-hosted

    steps:
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download SonarQube Zip
        shell: pwsh
        run: |
         Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
         Invoke-WebRequest -Uri "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.4.1.88267.zip" -OutFile "sonarqube.zip"

      - name: Start SonarQube
        run: |
          cd "$env:USERPROFILE\sonarqube\sonarqube-10.4.1.88267\bin\windows-x86-64"
          Start-Process -FilePath StartSonar.bat
          Start-Sleep -Seconds 60  # wait for server to initialize

      - name: Check SonarQube Status
        run: |
          $status = Invoke-RestMethod -Uri http://localhost:9000/api/system/status
          Write-Host "SonarQube status: $($status.status)"
